### ISSUE TITLE
pymongo.errors.OperationFailure: Authentication failed. 求助

### ISSUE THREAD

**Issue by lpcheng1208** [tinybees/aclients#3]
一直认证出错,mongo版本是4.0的,如何修改认证方式呢

**Comment by tinybees** [comment]
你用工具或者命令行连接mongo可以吗？我这里一切正常

**Comment by lpcheng1208** [comment]
工具是可以的,请问一下你的mongo版本是多少呢?

**Comment by lpcheng1208** [comment]
from aclients import AIOMongoClient
mon_db = AIOMongoClient()
mon_db.init_app(app)
app.mmm = mon_db


test_mmm = request.app.mmm
j = await test_mmm.find_document(name='actor', query_key={"rid": 2000479})

就一直抛出认证错误,但是我用命令行是可以正常的查询的,请教一下是否我初始化出了什么问题

**Comment by lpcheng1208** [comment]
数据库config 我有按照规则更新到app 的config里面了

**Comment by tinybees** [comment]
这里mongo的版本是有要求的，具体多少因为没有写文档所以不好给你说，我用的是3.6.12的版本

**Comment by lpcheng1208** [comment]
好的,谢谢
